# Generated by Django 4.2.5 on 2023-12-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_comment_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(verbose_name='creation time'),
        ),
    ]
